### ISSUE TITLE
Course Info Update

### ISSUE THREAD

**Issue by SamTheDude** [EnactusSheffieldCodeCreators/codecreators-website#2]
The information on the website is from the old site, it needs updating with the new dates as well as any other information that may have changed about the course.

**Comment by charrink** [comment]
Replacement description for beginner's course:
An 8 week introductory course to Python, ideal with those with little to no prior programming experience. By committing only 2 hours per week, you will learn all the skills you need to start making your own Python projects! Sessions are held on Sundays at 1pm, and are recorded for students who miss a live session. Attending all the lectures will be rewarded with a certificate of completion, and handing in the final project will be rewarded with a certificate of commendation.
